# coding: utf-8

"""
    Creditas OpenAPI

    This is specification of the Creditas OpenAPI. It contains definitions of Creditas banking services exposed via API accessible on the internet.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: is@creditas.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.payment_order_foreign_partner_account import PaymentOrderForeignPartnerAccount  # noqa: E501
from swagger_client.rest import ApiException


class TestPaymentOrderForeignPartnerAccount(unittest.TestCase):
    """PaymentOrderForeignPartnerAccount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentOrderForeignPartnerAccount(self):
        """Test PaymentOrderForeignPartnerAccount"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.payment_order_foreign_partner_account.PaymentOrderForeignPartnerAccount()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
