# coding: utf-8

"""
    Creditas OpenAPI

    This is specification of the Creditas OpenAPI. It contains definitions of Creditas banking services exposed via API accessible on the internet.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: is@creditas.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.account_transaction_filter import AccountTransactionFilter  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountTransactionFilter(unittest.TestCase):
    """AccountTransactionFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountTransactionFilter(self):
        """Test AccountTransactionFilter"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.account_transaction_filter.AccountTransactionFilter()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
