# coding: utf-8

"""
    Creditas OpenAPI

    This is specification of the Creditas OpenAPI. It contains definitions of Creditas banking services exposed via API accessible on the internet.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: is@creditas.cz
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response20015 import InlineResponse20015  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse20015(unittest.TestCase):
    """InlineResponse20015 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015(self):
        """Test InlineResponse20015"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response20015.InlineResponse20015()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
